.vscode/settings.json
assets/css/theme.css
assets/js/theme.js
index.html
shop(1).html

Closes #20 
added navigation button to <strong>bottom right </strong> which further improves accessibility and enhances user experience.

added navigation button to quickly move to the top

---

cart(1).html
stylesheet.css

I had improved the cart page of the website.
Please review my pull request.

Improved the cart page

---

README.md

Rewritten the README.md file in an organized way.
Issues #14

Redesigned the README.md file 

---

assets/css/theme.css
stylesheet.css

Shifted the logo to left from current position so that it looks better and also rounded logo.

	modified:   assets/css/theme.css 

---

assets/css/theme.css

I have added the hover effect on the buttons, I added the text colour as a variant of red #E91E63 which is primarily used in the website texts or in the background of buttons and the background colour as white upon hovering over it, this colour combination made the website to remain similar with the overall theme and look aesthetic.
I also used the transform(scale) property to give the button a slight animation, and realization to the users that he is hovering over the buttons.
https://sahajoydeep.github.io/krishiconnect/  (preview)
Similarly, I tried using transform on the sections of the card using the hover effect, which visually enhances the interactivity on the website, and created an new issue for that feature please assign the new issue #86 
Thank You for giving me the opportunity

Hover Effect On Buttons Issue #37

---

faq(1).html

The FAQ section on the organization's website currently displays questions in a disordered sequence, which may disrupt user experience and clarity. To address this issue, I have reordered the questions to improve the flow and organization of the FAQ section and added mail to link.

fix FAQ section by reordering questions #8

---

shop(1).html

the cards on shop page were previously of unequeal size which has now been fixed!
before:
after:

[REPOST] make all the cards of same size

---

index.html

I have successfully added social links, when you click particular icon it will get redirected to particular site, If you provide your respective social media Id i can able to add that also for example when you click instagram icon it will get redirected to your instagram page.

social link working

---

shop(1).html

##What does that PR does?
This PR adds the hovering effect for the cards . 
fixe #40 
https://github.com/Anushkabh/krishiconnect/assets/130372618/30ecb24a-8ed0-429d-a996-cf143ee4c793

fix:Add hover to cards

---

about(1).html
assets/css/theme.css
cart(1).html
checkout(1).html
contact(1).html
faq(1).html
home.html
index.html
login.html
schemes.html
setting(1).html
shop(1).html
success.html
transaction.html

Hello PA, 
Fixed Issue No. #15 
and I have made changes in all the HTML files and assets/css/theme.css

Fixed Footer issue #15

---

assets/css/theme.css
index.html
script.js
shop(1).html

Resolves #76 
Hey @Anushkabh , I've fixed a few typos in the website and also removed unnecessary commented which i found in the process.
Additionally i also added the favicon for the website (logo from assets/img/logo)
Kindly check the changes and merge the PR
Let me know if any further changes.
Thank You!
Looking forward to contribute more

fixed typos

---

assets/css/theme.css
index.html

fixed: #89
I have added the hovering effect for the cards and also added the box shadow effect, added the hovering effect for icons as well,
for title, I applied a shadow effect by hovering the title .

shop now section is improved #89

---

cart(1).html
stylesheet.css

https://github.com/Anushkabh/krishiconnect/assets/138794574/3935ce5b-6002-41ef-99ae-83101086a2f3

improvement in cart section

---

faq(1).html

I have resolved the issue #137 and corrected all the mentioned issues.

Done corrections in faq(1).html

---

about(1).html
cart(1).html
contact(1).html
faq(1).html
home.html
login.html
schemes.html
setting(1).html
shop(1).html
success.html
transaction.html
wishlist.html

Added Website Title to KrishiConnect Pages

---

index.html

Now on every page of the website favicons are visible . Hence fixed issue #129 .
Here are some screenshots : 
Thank you.

Fixed issue #129

---

wishlist.html

Fixes #119 
Added Home button in the wishlist and also fixed alignment of navbar-items
**Before:**
**After:**

fixed navitems to be aligned and added home page to wishlist

---

cart(1).html
shop(1).html
transaction.html

I have added icons on the navbar of of my cart transaction and shop
This PR fixes #100

Added icons on navbar 

---

index.html
shop(1).html
shop.js
toast.js

I tried to add the toasts on right top corner, bus was not able to, maybe because we would have to change entire page CSS. 
So I came up with this idea though, which appears on the top of the page.

[FIX] #106 Added Toast Notifications 

---

about(1).html
cart(1).html
checkout(1).html
faq(1).html
index.html
login.html
schemes.html
setting(1).html
shop(1).html
success.html
transaction.html
wishlist.html

issue #108
Login Page After Changes :
https://github.com/Anushkabh/krishiconnect/assets/154777864/c4366a46-1d71-4c3c-846f-a3be51a398a1

Feat: Reveal items on scroll!!

---

shop(1).html

@Anushkabh the issue #157 has been rectified. Kindly accept the pull request to incorporate changes. I am a GSSOC'24 contributor.

add to cart button alert added wrt issue #157

---

about(1).html
cart(1).html
contact(1).html
faq(1).html
index.css
index.html
login.html
shop(1).html
transaction.html

@Anushkabh I have solved the problem of alignment of the logo of krishiconnect on multiple pages wrt to issue #155 . Additionally there was another issue that "shop" in the navbar was showing twice, that too I have resolved.

Krishiconnect logo alignment done issue #155

---

login.html
stylesheet.css

@Anushkabh 
I have successfully updated the Sign up/Login page and gave it the look, which make the webpage professional and attractive
This is before changes
and this is the end product (after the changes)
Fixes issue #188

Updated the Login/Sign up page

---

assets/css/theme.css
cart(1).html
index.html
stylesheet.css

FOOTER UPGRADED

---

shop(1).html

The issue with the shop(1).html page not being responsive on mobile devices has been resolved. Additionally, the navbar has been updated to ensure proper functionality and appearance on mobile devices.
1. Responsive Design:
- Updated CSS to include responsive design practices.
- Added media queries to adjust layout, images, text, and buttons for various screen sizes.
- Ensured all elements resize and reposition appropriately for mobile view.
2. Navbar Update:
- Enhanced the navbar to be fully responsive.
- Fixed layout and alignment issues for mobile view.
- Ensured dropdown menus and links are easily accessible on smaller screens.
The shop(1).html page and navbar now display correctly on mobile devices without overflow, misalignment, or functionality issues.
@Anushkabh , kindly merge …

fixed-issue-#143

---

shop(1).html

Fixes issue #121 
Hello, I have improved the Hero section of Shop page. Now it looks responsive and also now the text is not overlapping with the background image.
Please check it once and let me know if changes to me made. Thank you.

Enhancement: Improved hero section of shop page.

---

contact(1).html
index.html

Hello PA,
I have found that contact us page file was not linked properly.It shown the error message when we clicked contact page.
https://github.com/Anushkabh/krishiconnect/assets/169278740/4a869410-5f41-4186-9b61-0b84a57ec614
and  in the contact page even if we do not fill any details ,the form accepted it.
So I made changes and linked the contact(1).html file properly with index.html .Also I made the form fields in contact page as required.
https://github.com/Anushkabh/krishiconnect/assets/169278740/2e080046-2360-4bf5-b6c6-32d00ac8f37b
@Anushkabh please accept this PR under GSSOC 2024 and add appropriate labels to it.
Thank you.

Fixed contact us page #117

---

README.md

Hey @Anushkabh ,
I have updated the file as per your request; once check out the changes, merge it

Updated the screenshots in README.md

---

cart.js

#166 
- The `cart` page bug has been solved.
- If add the `delete` icon to click the cart page product has been delete new one can be added.
- please merge and rock it.. :rocket: 
[Screencast from 2024-05-17 12-02-20.webm](https://github.com/Anushkabh/krishiconnect/assets/121082414/3c0f6b21-3dc8-4112-98ce-ac6079d5d121)
[Screencast from 2024-05-20 20-11-03.webm](https://github.com/Anushkabh/krishiconnect/assets/121082414/6eb1e848-bde7-4ad4-a1a9-e68941b8f7ae)

[BUG] : Cart page Quantiy fixed

---

cart(1).html

I have added favicon to the web page.

Favicon added

---

index.css

Text visible now!

---

login.html

This PR fixes the issue regarding the  navbar collision with hero section in Farmer's login page.
Fixes #278 
https://github.com/Anushkabh/krishiconnect/assets/130372618/41d05b26-92c0-4019-a21a-4100a2b127b9
##How to test this?
1.Open login.html file
2. Go to navbar and scroll the page.

Fix:Navbar-hero

---

shop(1).html

Hello Project Admin,
Fixes  - #40 (Adding Hovering Effect to the Cards)
This pull request updates the product cards in the shop(1).html file. It includes a new HTML structure and CSS styling for a better presentation of the product cards where I included a hovering effect for all the shopping cards and the code is checked precisely and considered with all due respect to the guidelines.
**Changes Made:**
- Implemented hover effects on the Product Cards Section to enhance user interaction and visual feedback.
- Adjusted hover effects to ensure better visibility and aesthetic appeal compared to the previous implementation.
- Improved color contrast and vibrancy of the hover effect to make it more noticeable and engaging for users.
- The Previous UI's hovering was not visible efficiently, I …

Updated Added Hovering to cards in  Shop categories

---

assets/css/theme.css
contact(1).html

#Fixed issue #267 
I have changed the banner image on the top which is going with the website theme and also added some CSS to make the form look better.
Kindly Merge this pull request  @Anushkabh
Screenshot / Videos:
https://github.com/Anushkabh/krishiconnect/assets/132553685/86fbc94a-6b1f-413c-8e1b-e2ce64a179f2

Update the Contact section

---

index.html

#325 I solved the issue 325. I changed the documentation.

changeDocumentation

---

faq(1).html

Resolved issue #326 
@Anushkabh Please check and let me know if any changes are required

Updated FAQ Page

---

shop(1).html

**Fixes**: #282 
**Add to Cart is now at center!!**
**Before**:
**After**:

Add to Cart is now at center

---

shop(1).html

**Fixes**: #312
Vegetables, Fruits, Oils seeds etc are now redirecting to their correct sections . Please take a look!!

Vegetables, Fruits, Oils seeds etc are now redirecting to their correct sections

---

darkmode.css

Hello @Anushkabh , fixes: #328 
- In this issue can be fixed.
- please merge it and rock it... :rocket: 
[Screencast from 2024-05-25 17-54-41.webm](https://github.com/Anushkabh/krishiconnect/assets/121082414/df78cb90-9ced-4327-afce-e15c7e009efc)
[Screencast from 2024-05-27 19-11-30.webm](https://github.com/Anushkabh/krishiconnect/assets/121082414/1b26a652-c6af-47c2-a208-3ef434547a22)

[BUG] : Dark & Light mode doesn't proper fixed

---

index.css
index.html

@Anushkabh 
i created hover effect on image card with 3d animations 
you can check that and merge it
without hover effect:
with hover effect:
closed #258

img card completely done with hover effect

---

login.html
stylesheet.css

Fixes #298
Successfully corrected the alignment of navbar on login page

Corrected the alignment on navbar of login page

---

.vscode/settings.json
about.html
assets/css/theme.css

This is pull request for adding User Testimonials feature as mentioned in issue #227.
Kindly let me know if any more changes are required.

Added User testimonials Section

---

wishlist.html

REMOVED EXTRA ICONS IN WISHLIST

---

index.html

Fixes #358 
Hope you will merge this into your repo

Corrected the homepage

---

index.html

fixed #356 
https://github.com/Anushkabh/krishiconnect/assets/83546205/38f1d13d-ef76-4df0-9f98-c0a60ca25a93
The changes have been made @Anushkabh

the cards UI have been improved for mobile devices

---

fruites.css
fruites.html
shop(1).html

@Anushkabh 
description:
Feat: Add Beautiful Detailed Fruits Page #345
close #345
check this out: 
- i created `fruits` page when user click on fruits 
- they will redirect to this page [route: `/fruits`]
- also added hover effect on fruits card
- in responsive it look like

Fruites page

---

cart(1).html
shop(1).html
transaction.html
wishlist.html

make navbar responsive

---

transaction.html
transaction.js

IF THERE IS NO TRANSACTION NOW IT WILL SHOW

FIXED::BUG: No Transcation PAge #361

---

cart(1).html
shop(1).html
transaction.html

fixes: #302 
Navbar of Shop, Transactions & My Cart section is now fixed at the top
Shop:
Transactions:
My cart:

Navbar of Shop, Transactions & My Cart section is now fixed at the top

---

index.html
shop(1).html

Fixed a typo Error on shop.html  file
fixed alt for images on index.html file

typo and alt edit

---

index.html
stylesheet.css
wishlist.html

Wishlist UI/UX Transformed Including its Footer
Code Modified- ID and Classes Added to Footer

Wishlist UI/UX Transformed Including its Footer

---

about(1).html
about.html
cart(1).html
checkout(1).html
contact(1).html
index.html

Solved contact.html 404 Not found
Resolved the path issue for the same

Solved contact.html 404 Not found

---

cart(1).html
cart.css
darkmode.css
stylesheet.css
wishlist.html

Redesigned cart.html webpage Issue #364

Redesigned cart.html webpage Issue #364

---

cart(1).html
cart.css
darkmode.css
stylesheet.css
wishlist.html

Reverts Anushkabh/krishiconnect#478

Revert "Redesigned cart.html webpage Issue #364"

---

cart(1).html
contact(1).html
home.html
login.html
shop(1).html
transaction.html

Fixes: #413
https://github.com/Anushkabh/krishiconnect/assets/169196836/88d9c636-8177-4dd8-bd1f-ec657ae9dd97

navbar fixed for mobile screen

---

index.html

Hello PA,
fixed issue - #450
I have removed the git conflict code from website.
before-
after-
@Anushkabh @RitiChandak  Please accept this PR under GSSOC 2024 and add appropriate labels to it.

fixed issue: #450

---

shop(1).html

Colour changed to rgb(44,43,43) in relation to other website colours so that the text is visible on shopping page.
Issue #410 
Screenshots for reference -
:: Before -
:: After-

Update shop(1).html - Visibilty of text on Shopping Page

---

login.html
stylesheet.css

Closes #416
- Created a modern looking Register/Login form.
- Login and Signup is working properly and user is able to actually Sign-up/Login through this form.
- Responsive for all screen sizes.
Kindly review and merge this PR under GSSOC'24.

Created register and login functionality.

---

fruites.html
vegetables.html

I have updated the content and about us section on both fruits and vegetable page.
Fixes #425

Updated- Fruits and Vegetable page

---

shop(1).html

Hover  effect bug solved in the footer
https://github.com/Anushkabh/krishiconnect/assets/125277258/c29bd1f6-78b9-4b7c-ab1e-348fe05bd32d

Hover  effect bug solved in the footer

---

shop(1).html

Add Ratings

---

about(1).html
cart(1).html
index.html
login.html
shop(1).html
transaction.html

Hello PA,
Fixed issue - #398 
There was a wrong file name , instead of contact(1).html it was Contact(1).html so I changed it  in all pages.
before-
After-
Accept my PR under GSSOC 2024 and add appropriate labels. @Anushkabh

Fixed issue#398

---

Miscellenous.css
Miscellenous.html
shop(1).html

@RitiChandak 
Description: 
Feat: Design beautifully MISCELLANEOUS page #434
close #434 
please check this
i designed miscellenous page with responsive too
in responsive screen
hover effect:

Miscellenous page

---

wishlist.html

Helllo @Anushkabh 
fixed issue - #464 
I fixed the overlap problem of buttons on wishlist page
before-
https://github.com/Anushkabh/krishiconnect/assets/169278740/724bd12d-8246-4aa7-9227-38016430d1b3
after-
https://github.com/Anushkabh/krishiconnect/assets/169278740/cacc48d6-dd77-4763-8590-9ef4f350088e
Accept this PR under GSSOC 2024 and add appropriate labels to it.

fixed : wishlist page buttons get overlap on hover #464

---

login.html

This PR fixes #305 
I have included the forgot password in the login it redirects the user to the sign-up page. Let me know if any changes has to be made..

Added Forgot Password

---

cart(1).html

Fixed issue: #485 
Refactored the button elements for "Empty Cart" and "Checkout" to include text and vector inside the button tags. This change improves the semantic structure and ensures the vector and text are properly associated with the button actions.

Refactor button elements to include text and vector inside the button tags

---

cart(1).html
cart.css

Fixes Issue #516 
Changes made:
1. Removed buttons from Enter your details section and added them under Your cart section
2. User will be redirected to the "Checkout" page after clicking on "Order Now"
3. User will be redirected to the "Shop" page after clicking on "Continue"

Fixed BUTTONS in the cart

---

shop(1).html

the taglines have been enhanced making them more memorable and recognizable to customers.

enhanced the taglines in shopping page

---

shop(1).html

This pull request includes changes to the representation and functionality of the rupee coin in our project.
Closes issue - #244
**Details:**
- Modified the design of the rupee coin icon.
- Updated the value representation of the rupee coin in the currency module.
- Adjusted the calculation logic involving rupee coins in the financial transactions feature.
- Added new unit tests to ensure the accuracy of rupee coin-related functions.
**Impact:**
These changes will enhance the user interface and improve the accuracy of financial calculations involving rupee coins. All related functionalities have been tested to ensure no regressions.

Changed rupee coin in all the cards!!!

---

contact(1).html
stylesheet.css

#520 
@RitiChandak 
check it and merge it 
also add label gssoc and level1 ,2,3 ..

contact.html file do in set and also give well structure

---

shop(1).html
shop.js
toast.js

i added toaster instead of alert message

toastify design secessfully

---

login.html
stylesheet.css

Seller page is set !!!

---

transaction.html
vegetables.html
wishlist.html

In the pages vegetables, wishlist and transaction due to black font color, it isn't very well visible. I added the white translucent bg where ever needed.
Fixes - #553

added bg for visibility

---

shop(1).html
shop.js
toast.js

Reverts Anushkabh/krishiconnect#556

Revert "toastify design secessfully"

---

contact(1).html

issue no #549
Shown message when submit form.
After submit form will be reset.
Show alert when any field is left to fill.

Message added after submit contact form

---

index.html
rateus.css
rateus.html

Hello Project Admin
I added Rate Us Option - #565 
Kindly please go through it
https://github.com/Anushkabh/krishiconnect/assets/161804629/1e120235-7dda-4f4a-865e-c65f64fb1e36

Added Rate Us Option

---

assets/css/theme.css
assets/packages/o2system-ui/scss/o2system-ui/_utilities.scss
cart(1).html
login.html
shop(1).html
transaction.html

i completed navigation remain same in whole pages or website 
BUG:navigation not remain same in whole website #518 
merged it and close it

navigation same in whole website

---

README.md

contributors section added

---

index.html

Hey @Anushkabh,
issue closes #567 
I resolved the inconsistent behavior of The Scroll-to-top button which were moving unpredictably, appearing in different positions on the screen, which was not the expected behavior.
Now the scroll-to-top button is functioning well.
**Video File**
https://github.com/Anushkabh/krishiconnect/assets/131389695/3293df4c-9d33-4da0-b999-9f0828f76d5f
@Anushkabh,Thank you for considering my contribution. I look forward to your feedback.

RESOLVED :  Scroll-to-Top Button Inconsistent Positioning

---

src/shop.html

Replaced rp with ₹ because ecommerce websites dont have rp they have ₹ only .
closes #634

Replaced Rp with ₹

---

index.html

Added a new FAQ tab to the footer for better accessibility and user navigation.
Updated the footer layout to accommodate the new tab without affecting the existing design.
Ensured the FAQ tab links correctly to the FAQ page.
Conducted tests to verify that the new tab functions correctly across different browsers and devices.
These enhancements aim to improve the user experience by providing easy access to frequently asked questions.
Please review the changes and provide feedback.

Issue #569 Solved, Added FAQ tab on the footer 

---

src/cart.html

My issue no: #589 
I have made input fields to work properly. Now the input fields are working properly.
Please add GSSOC 
https://github.com/Anushkabh/krishiconnect/assets/143276011/4ed56268-8b1d-4d05-87df-170fd289d9e6
label and level.

input fields are working

---

src/shop.html

This pull request addresses the following updates:
Price Formatting:
Converted prices to display two digits after the decimal point (e.g., ₹120.45 instead of ₹120.456).
Price Adjustments:
Updated prices for various shop items to reflect current Indian market rates: (approx)
Mangos: ₹120.45
Fruits: ₹80.75
Vegetables: ₹45.87
Oils: ₹150.99
Discount Adjustments:
Modified discounts accordingly to match the updated prices.

ISSUE #615 Updated Shop

---

assets/js/cart.js

Hey, the issue #563 has been resolved. Kindly merge the pull request. Thanks
https://github.com/Anushkabh/krishiconnect/assets/110047194/81bf67e4-ffc3-4e7f-831c-80cf282ce941

Fix | issue #563

---

chatBot/style.css

fixed the chat bot

---

assets/css/rateus.css
src/rateus.html

Hello Project Admin
I Added Toastify Message - Solved #607
Kindly Please go through this PR @himanshu-03 
https://github.com/Anushkabh/krishiconnect/assets/161804629/c8afce69-617a-41f6-b567-e76b30475e78

Added Toastify Message

---

assets/css/Footer-new.css
index.html
src/about.html
src/cart.html
src/checkout.html
src/contact.html
src/detail-product.html
src/faq.html
src/feedback.html
src/fruites.html
src/home.html
src/login.html
src/miscellenous.html
src/schemes.html
src/setting.html
src/shop.html
src/success.html
src/transaction.html
src/vegetables.html
src/wishlist.html

fixes #712 
Description:
- Added links to the footer on all pages.
- Changed the logo in the footer on all pages.
- Redirected pages that have not yet been created to the same page.
Screenshot:-
https://github.com/Anushkabh/krishiconnect/assets/146121869/8f323f05-e7ab-4865-98cd-244900c578de

Added links to the footer and changed the logo in the footer on all pages

---

index.html

Added FAQ section in the nav bar
closes #734

Made changes in the nav bar

---

assets/js/cart.js
src/cart.html
src/contact.html
src/login.html
src/shop.html
src/transaction.html

solves: #648 
I have added the thank you modal. It has a "ok" button which closes the modal. I have also added confetti effect.
https://github.com/Anushkabh/krishiconnect/assets/152094228/15507e98-aeef-4f6a-b646-ceaff2115b3d

added thank you modal

---

assets/css/faq.css
src/faq.html

Corrected Footer on FAQ Page

---

index.html

Closes issue: #780 
I have added the appropriate meta tags for making the website SEO friendly.
Kindly let me know if there are any changes to be made.

appropriate SEO tags are added

---

assets/css/Footer-new.css

Fixes #799 
This pull request addresses the issue of footer text alignment on mobile screens. The changes ensure that the footer text is properly aligned, providing a consistent and visually appealing layout across different devices.

Solved issue 799

---

assets/css/darkmode.css
src/contact.html

Now the contact page is looking fine in dark theme.
https://github.com/Anushkabh/krishiconnect/assets/121669832/5c813019-2e94-4d5f-ae71-096d1b0e8075
Please check and let me know if any changes, Thank you.

Added darkmode toggle with styles.

---

index.html

Solved the problem that was coming due to chatbot. #789

Updated chatbot #789

---

assets/css/test-style.css

issue : #632 
I done all the changes as per request , proper alignment of card, removing of border and hovering effects.
@Anushkabh and @himanshu-03 ,I added new PR due to conflicts and closed previous PR, please check the changes and merge the changes as soon as possible to avoid conflicts.
Thank you

Feature : Border removed and making proper alignment

---

index.html

Issue: #873 
Added an impressive feedback on Client Feedback cards.
https://github.com/user-attachments/assets/39c11489-7e73-41a4-a936-41b0cfccd523

Client Feedback added

---

package-lock.json
src/login.html

closes #915 @Anushkabh please review this PR.

Seller form added

---

src/faq.html

closes #905 
Added the FAQ to the page and make it working too.
@Anushkabh please review this PR asap.

Added the FAQ section to the website

---

index.html
src/cart.html
src/contact.html
src/login.html
src/privacypolicy.html
src/rateus.html
src/shop.html
src/termsandconditions.html
src/transaction.html
src/wishlist.html

I have made the navbar sticky in all the pages .

Made the navbar sticky in all the pages .

---

index.html
src/contributors.html

Hey @RitiChandak 
- Issue Closes #917
I have created Contributors Page Which Supports Both Dark mode and light mode theme.
- Created `contributors.html` page
- Added Suitable `Hover` Effects
- Added `Dark mode` theme and `Light mode` theme styles
- Adjust the contributors cards
- Added Similar `Navba`r and `Hamburger` in Mobile View
- Added `Footer`
- Added `Scroll down progress bar` for consistency 
- Made it complete `responsive` for all devices.

Design "Our Contributors" Page 
